(Generated by SketchUcam V1.3a)
(File: TestAluminumCircle.skp)
(Bit diameter: 5.0mm)
(Feed rate: 500.0mm/min)
(Plunge Feed rate: 100.0mm/min)
(Material Thickness: 2.0mm)
(Material length: 2200.0mm X width: 1200.0mm)
(Overhead Gantry: true)
(Multipass enabled, Depth = 0.1mm)
(Optimization is ON)
(www.PhlatBoyz.com)
G90 G21 G49  G17
M3 S18000
G00 Z10.000

G00 X0 Y0 (home)
M05
M30
